### ISSUE TITLE
Create a pull request template

### ISSUE THREAD

**Issue by MarchandMD** [club-40/odin-pantry#41] opened 2023-12-17 00:00 UTC
## Description:
as a developer
when I make a pr
I want the body of the PR to have a PR template for me to complete

## Tasks:
- [ ] Add a PR template

## Resources: 
- [ ] [a list of pr template examples from GH](https://github.com/stevemao/github-issue-templates)

## Additional remarks:
Probably a good initial setup step to allow people to create issues

**Comment by Philip-Clark** [comment] 2023-12-18 23:10
@MarchandMD is this a possible duplicate of #33 ?

Or are you talking about **PR templates** and not **Issue templates**?
I think both are probably worth implementing but wanted to clarify as the link you shared has both Issue and PR templates, and you mentioned "Probably a good initial setup step to allow people to create issues".

**Comment by MarchandMD** [comment] 2023-12-18 23:12
Forgive the mixed message on my issue; Yeah, I'm talking about PR templates. 

And I'm happy to throw a review on that issue template issue you've got

**Comment by Philip-Clark** [comment] 2023-12-18 23:17
@MarchandMD Sounds great. I'll look into adding PR templates unless this is something you would like to do.

A review of the PR I made would be great. I'd love input on what types of templates we should implement as well

**Comment by Philip-Clark** [comment] 2023-12-20 20:40
PR #43 will close this upon merge.
Awaiting review.

**Closed** 2023-12-20 22:24 UTC
